### CREATE a new title
POST http://localhost:3000/title-basics/create
Content-Type: application/json

{
  "tconst": "tt1234567",
  "titleType": "movie",
  "primaryTitle": "Test Movie",
  "originalTitle": "Test Movie Original",
  "isAdult": 0,
  "startYear": 2025,
  "endYear": null,
  "runtimeMinutes": 120,
  "genres": "Drama"
}

### READ a single title by ID
GET http://localhost:3001/title-basics/read/tt1234567?startYear=2025

### READ ALL titles
GET http://localhost:3000/title-basics/readAll

### READ ALL titles (From Node variant)
GET http://localhost:3000/title-basics/readAllFromNode

### UPDATE a title by ID
PUT http://localhost:3000/title-basics/update/tt1234569
Content-Type: application/json

{
  "titleType": "movie",
  "primaryTitle": "Updated Movie Title",
  "originalTitle": "Updated Movie Original",
  "isAdult": 0,
  "startYear": 2026,
  "endYear": null,
  "runtimeMinutes": 130,
  "genres": "Action,Drama"
}

### DELETE a title by ID
DELETE http://localhost:3000/title-basics/delete/tt1234569?startYear=2025
