POST http://localhost:3000/title-basics/create
Content-Type: application/json

{
  "tconst": "tt1234567",
  "titleType": "movie",
  "primaryTitle": "Test Movie",
  "originalTitle": "Test Movie Original",
  "isAdult": 0,
  "startYear": 2025,
  "endYear": null,
  "runtimeMinutes": 120,
  "genres": "Drama"
}
